[build]
publish = "exampleSite/public"
command = "npm run build_netlify && cd exampleSite && hugo --themesDir=../.."

[context.production.environment]
HUGO_VERSION = "0.62.2"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "npm run build_netlify && cd exampleSite && hugo --enableGitInfo --themesDir ../.."

[context.split1.environment]
HUGO_VERSION = "0.62.2"
HUGO_ENV = "production"

[context.deploy-preview]
command = "npm run build_netlify && cd exampleSite && hugo --buildFuture -b $DEPLOY_PRIME_URL --themesDir ../.."

[context.deploy-preview.environment]
HUGO_VERSION = "0.62.2"

[context.branch-deploy]
command = "npm run build_netlify && cd exampleSite && hugo  -b $DEPLOY_PRIME_URL --themesDir ../.."

[context.branch-deploy.environment]
HUGO_VERSION = "0.62.2"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
