[build]
publish = "public"
command = "npm run build_netlify && hugo --source=exampleSite --destination=../public"

[context.production.environment]
HUGO_VERSION = "0.62.2"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "npm run build_netlify && hugo --source=exampleSite --destination=../public --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.62.2"
HUGO_ENV = "production"

[context.deploy-preview]
command = "npm run build_netlify && hugo --source=exampleSite --destination=../public --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.62.2"

[context.branch-deploy]
command = "npm run build_netlify && hugo --source=exampleSite --destination=../public -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.62.2"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
