[build]
  command = "npm run production && npm run fetch_project && hugo --gc --minify -b $URL --themesDir ../../ --source exampleSite"
  publish = "exampleSite/public"

[build.environment]
  HUGO_THEME = "repo"
  HUGO_VERSION = "0.62.2"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "npm run production && npm run fetch_project && hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL --themesDir ../../ --source exampleSite"

[context.branch-deploy]
  command = "npm run production && npm run fetch_project && hugo --gc --minify -b $DEPLOY_PRIME_URL --themesDir ../../ --source exampleSite"
