[en]
  languageName = "English"
  weight =  1
[fr]
  languageName = "Francais"
  weight =  2
[es]
  languageName = "Español"
  weight =  3
[pt]
  languageName = "Portuguesa"
  weight =  4
[jp]
  languageName = "日本語"
  weight =  5