
[[main]]
    name = "Examples"
    url = "#"
    weight = 2
    identifier = "examples"
    
[[main]]
    name = "Single Page"
    url = "/single_page/"
    weight = 1
    parent = "examples"
    
[[main]]
    name = "News sample"
    url = "/news/"
    weight = 2
    parent = "examples"
    
[[main]]
    name = "Membership sample"
    url = "/membership/"
    weight = 3
    parent = "examples"
    
[[main]]
    name = "Events sample"
    url = "/events/"
    weight = 3
    parent = "examples"
    
[[main]]
    name = "FAQ sample"
    url = "/faq/"
    weight = 4
    parent = "examples"
    
[[main]]
    name = "Hide Call For Action"
    url = "/hide_call_for_action/"
    weight = 5
    parent = "examples"

[[main]]
    name = "Without Breadcrumb"
    url = "/without_breadcrumb/"
    weight = 6
    parent = "examples"

[[main]]
    name = "Exemples de FAQ"
    url = "/faq/"
    weight = 4
    parent = "examples"

[[main]]
    name = "Components"
    url = "/components/"
    weight = 3
    identifier = "components"

[[main]]
    name = "Solstice Additions"
    url = "/components/#solstice"
    weight = 1
    parent = "components"
    identifier = "solstice"

[[main]]
    name = "Events Framework"
    url = "/components/#events-framework"
    weight = 2
    parent = "components"
    identifier = "events"

[[main]]
    name = "Dynamic Content"
    url = "/components/#dynamic"
    weight = 3
    parent = "components"
    identifier = "dynamic"

[[main]]
    name = "Deprecated"
    url = "/components/#deprecated"
    weight = 4
    parent = "components"
    identifier = "deprecated"

[[main]]
    name = "Membership"
    url = "/components/members/"
    weight = 3
    parent = "solstice"    
    
[[main]]
    name = "Taxonomy list"
    url = "/components/taxonomy_list/"
    weight = 3
    parent = "solstice"
    
[[main]]
    name = "Testimonials"
    url = "/components/testimonials/"
    weight = 3
    parent = "solstice"
    
[[main]]
    name = "YouTube videos"
    url = "/components/youtube/"
    weight = 3
    parent = "solstice"
    
[[main]]
    name = "FAQ"
    url = "/components/faq/"
    weight = 4
    parent = "solstice"
    
[[main]]
    name = "Featured Footer"
    url = "/components/featured_footer/"
    weight = 3
    parent = "solstice"
    
[[main]]
    name = "Featured Story"
    url = "/components/featured_story/"
    weight = 3
    parent = "solstice"
    
[[main]]
    name = "Project list"
    url = "/components/project_list/"
    weight = 3
    parent = "solstice"
    
[[main]]
    name = "EclipseFdn Project list"
    url = "/components/eclipsefdn_projects/"
    weight = 3
    parent = "solstice"
    
[[main]]
    name = "HTML Tables"
    url = "/components/tables/"
    weight = 3
    parent = "solstice"
    
[[main]]
    name = "RSS Feed"
    url = "/components/rss/"
    weight = 3
    parent = "dynamic"
    
[[main]]
    name = "RSS Feed"
    url = "/components/rss/"
    weight = 3
    parent = "dynamic"
    
[[main]]
    name = "Users Display"
    url = "/components/user_display/"
    weight = 3
    parent = "events"
    
[[main]]
    name = "User Bios"
    url = "/components/user_bios/"
    weight = 3
    parent = "events"
    
    
[[main]]
    name = "Registration"
    url = "/components/registration/"
    weight = 3
    parent = "events"
    
    
[[main]]
    name = "Agenda"
    url = "/components/agenda/"
    weight = 3
    parent = "events"
    
[[main]]
    name = "Newsroom News"
    url = "/components/newsroom/news/"
    weight = 3
    parent = "dynamic"
    
[[main]]
    name = "Newsroom Events"
    url = "/components/newsroom/events/"
    weight = 3
    parent = "dynamic"
    
[[main]]
    name = "News"
    url = "/components/news/"
    weight = 2
    parent = "deprecated"

[[main]]
    name = "Events"
    url = "/components/events/"
    weight = 3
    parent = "deprecated"
    
[[sidebar]]
    name = "Hugo Solstice Theme"
    url = "/"
    weight = 3
    identifier = "home"
      
[[sidebar]]
    name = "Component list"
    url = "/components"
    weight = 1
    parent = "home"
    pre = "<i class=\"fa fa-chevron-right fa-fw\"></i>"
    identifier = "component-list"
    
[[sidebar]]
    name = "GitHub repository" 
    url = "https://github.com/EclipseFdn/hugo-solstice-theme"
    weight = 2
    parent = "home"
    pre = "<i class=\"fa fa-github fa-fw\"></i>"

[[sidebar]]
    name = "Third parent"
    url = "/third-parent"
    weight = 2
    pre = "<i class=\"fa fa-github fa-fw\"></i>"
    identifier = "third-parent"

[[sidebar]]
    name = "test children"
    url = "/third-parent/test-children"
    weight = 1
    parent = "third-parent"
    pre = "<i class=\"fa fa-chevron-right fa-fw\"></i>"
    identifier = "test-children"

[[sidebar]]
    name = "test children 2"
    url = "/third-parent/test-children-2"
    weight = 1
    parent = "third-parent"
    pre = "<i class=\"fa fa-chevron-right fa-fw\"></i>"
    identifier = "test-children-2"

[[sidebar]]
    name = "test children's children-1"
    url = "/third-parent/test-children/test-children-children"
    weight = 1
    parent = "test-children"
    pre = "<i class=\"fa fa-chevron-right fa-fw\"></i>"

[[sidebar]]
    name = "test children's children-2"
    url = "/third-parent/test-children/test-children-children-2"
    weight = 2
    parent = "test-children"
    pre = "<i class=\"fa fa-chevron-right fa-fw\"></i>"
    
[[sidebar]]
    name = "Membership"
    url = "#"
    weight = 4
    identifier = "membership"

[[sidebar]]
    name = "Sidebar Item 1"
    url = "#"
    weight = 2
    parent = "membership"
    pre = "<i class=\"fa fa-chevron-right fa-fw\"></i>"
