DefaultContentLanguage = "en"
title = "Hugo Solstice Theme"
theme = "hugo-solstice-theme"
metaDataFormat = "yaml"
googleAnalytics = ""
#disableKinds = ["taxonomy", "taxonomyTerm"]

[languages]
  [languages.en]
    languageName = "English"
    weight =  1
  [languages.fr]
    languageName = "Francais"
    weight =  2

[Params]
  google_tag_manager = ""
  description = "Eclipse Foundation: Solstice theme for Hugo."
  subtitle = "Eclipse Foundation"
  seo_title_suffix = " | The Eclipse Foundation"
  keywords = ["hugo", "solstice", "eclipse foundation"]
#  logo = "images/logo/eclipse-foundation-white.svg"
#  favicon = "images/favicon.ico"
  styles = "css/styles.css"
  js = "js/solstice.js"
  gcse = ""
  header_wrapper_class = "header-default-bg-img"
  call_for_action_text = "Download"
  call_for_action_url = "/downloads"
  call_for_action_icon = "fa-download"
  show_events = true
  table_classes = "table table-bordered"
  hide_cfa_same_page = true

[Author]
  name = "Christopher Guindon"
  website = "https://www.eclipse.org"
  email = "webdev@eclipse-foundation.org"
  facebook = "eclipse.org"
  twitter = "EclipseFdn"
  youtube = "EclipseFdn"
  googleplus = "+Eclipse"
  linkedin = "company/eclipse-foundation/"

[permalinks]
  news = "/:sections/:year/:month/:day/:slug/"

[taxonomies]
  category = "categories"
  tag = "tags"
  membership_level = "membership_levels"
  participation_level = "participation_levels"
  technology_types = "technology_types"
  build_technologies = "build_technologies"
  other_tags = "other_tags"

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true

[[languages.en.menu.main]]
    name = "Examples"
    url = "#"
    weight = 2
    identifier = "examples"
    
[[languages.fr.menu.main]]
    name = "Exemples"
    url = "#"
    weight = 2
    identifier = "examples"
    
[[languages.en.menu.main]]
    name = "Single Page"
    url = "/single_page/"
    weight = 1
    parent = "examples"
    
[[languages.fr.menu.main]]
    name = "Page seule"
    url = "/single_page/"
    weight = 1
    parent = "examples"
    
[[languages.en.menu.main]]
    name = "News sample"
    url = "/news/"
    weight = 2
    parent = "examples"
    
[[languages.fr.menu.main]]
    name = "Exemples de nouvelles"
    url = "/news/"
    weight = 2
    parent = "examples"
    
[[languages.en.menu.main]]
    name = "Membership sample"
    url = "/membership/"
    weight = 3
    parent = "examples"
    
[[languages.fr.menu.main]]
    name = "Exemples de Membres"
    url = "/membership/"
    weight = 3
    parent = "examples"
    
[[languages.en.menu.main]]
    name = "Events sample"
    url = "/events/"
    weight = 3
    parent = "examples"
    
[[languages.fr.menu.main]]
    name = "Exemples d'événements"
    url = "/events/"
    weight = 3
    parent = "examples"

[[languages.en.menu.main]]
    name = "FAQ sample"
    url = "/faq/"
    weight = 4
    parent = "examples"
    
[[languages.en.menu.main]]
    name = "Exemples de FAQ"
    url = "/faq/"
    weight = 4
    parent = "examples"

[[languages.en.menu.main]]
    name = "Components"
    url = "/components/"
    weight = 3
    identifier = "components"
    
[[languages.fr.menu.main]]
    name = "Composantes"
    url = "/components/"
    weight = 3
    identifier = "components"
 
[[languages.en.menu.main]]
    name = "News"
    url = "/components/news/"
    weight = 2
    parent = "components"
    
[[languages.fr.menu.main]]
    name = "Nouvelles"
    url = "/components/news/"
    weight = 2
    parent = "components"
    
[[languages.en.menu.main]]
    name = "Membership"
    url = "/components/members/"
    weight = 3
    parent = "components"
    
[[languages.fr.menu.main]]
    name = "Membres"
    url = "/components/members/"
    weight = 3
    parent = "components"
    
[[languages.en.menu.main]]
    name = "Taxonomy list"
    url = "/components/taxonomy_list/"
    weight = 3
    parent = "components"
    
[[languages.fr.menu.main]]
    name = "Liste de taxonomie"
    url = "/components/taxonomy_list/"
    weight = 3
    parent = "components"
    
[[languages.en.menu.main]]
    name = "Testimonials"
    url = "/components/testimonials/"
    weight = 3
    parent = "components"
    
[[languages.fr.menu.main]]
    name = "Témoignages"
    url = "/components/testimonials/"
    weight = 3
    parent = "components"
    
[[languages.en.menu.main]]
    name = "YouTube videos"
    url = "/components/youtube/"
    weight = 3
    parent = "components"
    
[[languages.fr.menu.main]]
    name = "Vidéos Youtube"
    url = "/components/youtube/"
    weight = 3
    parent = "components"
    
[[languages.en.menu.main]]
    name = "Events"
    url = "/components/events/"
    weight = 3
    parent = "components"
    
[[languages.fr.menu.main]]
    name = "Événements"
    url = "/components/events/"
    weight = 3
    parent = "components"

[[languages.en.menu.main]]
    name = "FAQ"
    url = "/components/faq/"
    weight = 4
    parent = "components"
    
[[languages.fr.menu.main]]
    name = "FAQ"
    url = "/components/faq/"
    weight = 4
    parent = "components"

[[languages.en.menu.main]]
    name = "Featured Footer"
    url = "/components/featured_footer/"
    weight = 3
    parent = "components"
    
[[languages.fr.menu.main]]
    name = "Pied de page en vedette"
    url = "/components/featured_footer/"
    weight = 3
    parent = "components"
    
[[languages.en.menu.main]]
    name = "Featured Story"
    url = "/components/featured_story/"
    weight = 3
    parent = "components"
    
[[languages.fr.menu.main]]
    name = "Article en vedette"
    url = "/components/featured_story/"
    weight = 3
    parent = "components"
    
[[languages.en.menu.main]]
    name = "Project list"
    url = "/components/project_list/"
    weight = 3
    parent = "components"
    
[[languages.fr.menu.main]]
    name = "Liste de projects"
    url = "/components/project_list/"
    weight = 3
    parent = "components"
    
[[languages.en.menu.main]]
    name = "EclipseFdn Project list"
    url = "/components/eclipsefdn_projects/"
    weight = 3
    parent = "components"
    
[[languages.fr.menu.main]]
    name = "Liste de projects d'EclipseFdn"
    url = "/components/eclipsefdn_projects/"
    weight = 3
    parent = "components"
    
[[languages.en.menu.main]]
    name = "HTML Tables"
    url = "/components/tables/"
    weight = 3
    parent = "components"
    
[[languages.en.menu.main]]
    name = "Tableaux HTML"
    url = "/components/tables/"
    weight = 3
    parent = "components"
    
[[languages.en.menu.main]]
    name = "RSS Feed"
    url = "/components/rss/"
    weight = 3
    parent = "components"
    
[[languages.en.menu.main]]
    name = "RSS Feed"
    url = "/components/rss/"
    weight = 3
    parent = "components"
    
[[languages.en.menu.main]]
    name = "Users Display"
    url = "/components/user_display/"
    weight = 3
    parent = "components"
    
[[languages.fr.menu.main]]
    name = "Users Display [fr]"
    url = "/components/user_display/"
    weight = 3
    parent = "components"
    
[[languages.en.menu.main]]
    name = "User Bios"
    url = "/components/user_bios/"
    weight = 3
    parent = "components"
    
[[languages.fr.menu.main]]
    name = "User Bios [fr]"
    url = "/components/user_bios/"
    weight = 3
    parent = "components"
    
[[languages.en.menu.main]]
    name = "Registration"
    url = "/components/registration/"
    weight = 3
    parent = "components"
    
[[languages.fr.menu.main]]
    name = "Registration [fr]"
    url = "/components/registration/"
    weight = 3
    parent = "components"
    
[[languages.en.menu.main]]
    name = "Agenda"
    url = "/components/agenda/"
    weight = 3
    parent = "components"
    
[[languages.fr.menu.main]]
    name = "Ordre du jour"
    url = "/components/agenda/"
    weight = 3
    parent = "components"

[[languages.en.menu.sidebar]]
    name = "Hugo Solstice Theme"
    url = "/"
    weight = 3
    identifier = "home"
    
[[languages.fr.menu.sidebar]]
    name = "Thème Solstice d'Hugo"
    url = "#"
    weight = 2
    identifier = "home"
    pre = "<i class=\"fa fa-chevron-right fa-fw\"></i>"
    
[[languages.en.menu.sidebar]]
    name = "Component list"
    url = "/components"
    weight = 1
    parent = "home"
    pre = "<i class=\"fa fa-chevron-right fa-fw\"></i>"
    
[[languages.fr.menu.sidebar]]
    name = "Liste des composantes"
    url = "/components"
    weight = 1
    parent = "home"
    pre = "<i class=\"fa fa-chevron-right fa-fw\"></i>"

    
[[languages.en.menu.sidebar]]
    name = "GitHub repository" 
    url = "https://github.com/EclipseFdn/hugo-solstice-theme"
    weight = 2
    parent = "home"
    pre = "<i class=\"fa fa-github fa-fw\"></i>"
    
[[languages.fr.menu.sidebar]]
    name = "Page GitHub"
    url = "https://github.com/EclipseFdn/hugo-solstice-theme"
    weight = 2
    parent = "home"
    pre = "<i class=\"fa fa-github fa-fw\"></i>"
    
[[languages.en.menu.sidebar]]
    name = "Membership"
    url = "#"
    weight = 3
    identifier = "membership"
    
[[languages.en.menu.sidebar]]
    name = "Sidebar Item 1"
    url = "#"
    weight = 1
    parent = "membership"
    pre = "<i class=\"fa fa-chevron-right fa-fw\"></i>"
    
[[languages.fr.menu.sidebar]]
    name = "Premier article"
    url = "#"
    weight = 1
    parent = "membership"
    pre = "<i class=\"fa fa-chevron-right fa-fw\"></i>"

    
[[languages.en.menu.sidebar]]
    name = "Sidebar Item 1"
    url = "#"
    weight = 2
    parent = "membership"
    pre = "<i class=\"fa fa-chevron-right fa-fw\"></i>"
    
[[languages.fr.menu.sidebar]]
    name = "Deuxième article"
    url = "#"
    weight = 2
    parent = "membership"
    pre = "<i class=\"fa fa-chevron-right fa-fw\"></i>"
    

