DefaultContentLanguage = "en"
title = "Hugo Solstice Theme"
theme = "hugo-solstice-theme"
metaDataFormat = "yaml"
googleAnalytics = ""
#disableKinds = ["taxonomy", "taxonomyTerm"]

[languages]
  [languages.en]
    languageName = "English"
    weight =  1
  [languages.fr]
    languageName = "Francais"
    weight =  2

[Params]
  google_tag_manager = ""
  description = "Eclipse Foundation: Solstice theme for Hugo."
  subtitle = "Eclipse Foundation"
  seo_title_suffix = " | The Eclipse Foundation"
  keywords = ["hugo", "solstice", "eclipse foundation"]
#  logo = "images/logo/eclipse-foundation-white.svg"
#  favicon = "images/favicon.ico"
  styles = "css/styles.css"
  js = "js/solstice.js"
  gcse = ""
  header_wrapper_class = "header-default-bg-img"
  call_for_action_text = "Download"
  call_for_action_url = "/downloads"
  call_for_action_icon = "fa-download"
  show_events = true
  table_classes = "table table-bordered"
  hide_cfa_same_page = true

[Author]
  name = "Christopher Guindon"
  website = "https://www.eclipse.org"
  email = "webdev@eclipse-foundation.org"
  facebook = "eclipse.org"
  twitter = "EclipseFdn"
  youtube = "EclipseFdn"
  googleplus = "+Eclipse"
  linkedin = "company/eclipse-foundation/"

[permalinks]
  news = "/:sections/:year/:month/:day/:slug/"

[taxonomies]
  category = "categories"
  tag = "tags"
  membership_level = "membership_levels"
  participation_level = "participation_levels"
  technology_types = "technology_types"
  build_technologies = "build_technologies"
  other_tags = "other_tags"

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true

[[menu.main]]
    name = "Examples"
    url = "#"
    weight = 2
    
[[menu.main]]
    name = "Single Page"
    url = "/single_page/"
    weight = 1
    parent = "Examples"
    
[[menu.main]]
    name = "News sample"
    url = "/news/"
    weight = 2
    parent = "Examples"
    
[[menu.main]]
    name = "Membership sample"
    url = "/membership/"
    weight = 3
    parent = "Examples"
    
[[menu.main]]
    name = "Events sample"
    url = "/events/"
    weight = 3
    parent = "Examples"

[[menu.main]]
    name = "FAQ sample"
    url = "/faq/"
    weight = 4
    parent = "Examples"

[[menu.main]]
    name = "Components"
    url = "/components/"
    weight = 3
 
[[menu.main]]
    name = "News"
    url = "/components/news/"
    weight = 2
    parent = "Components"
    
[[menu.main]]
    name = "Membership"
    url = "/components/members/"
    weight = 3
    parent = "Components"
    
[[menu.main]]
    name = "Taxonomy list"
    url = "/components/taxonomy_list/"
    weight = 3
    parent = "Components"
    
[[menu.main]]
    name = "Testimonials"
    url = "/components/testimonials/"
    weight = 3
    parent = "Components"
    
[[menu.main]]
    name = "YouTube videos"
    url = "/components/youtube/"
    weight = 3
    parent = "Components"
    
[[menu.main]]
    name = "Events"
    url = "/components/events/"
    weight = 3
    parent = "Components"

[[menu.main]]
    name = "FAQ"
    url = "/components/faq/"
    weight = 4
    parent = "Components"

[[menu.main]]
    name = "Featured Footer"
    url = "/components/featured_footer/"
    weight = 3
    parent = "Components"
    
[[menu.main]]
    name = "Featured Story"
    url = "/components/featured_story/"
    weight = 3
    parent = "Components"
    
[[menu.main]]
    name = "Project list"
    url = "/components/project_list/"
    weight = 3
    parent = "Components"
    
[[menu.main]]
    name = "HTML Tables"
    url = "/components/tables/"
    weight = 3
    parent = "Components"

    
[[menu.main]]
    name = "Agenda"
    url = "/components/agenda/"
    weight = 3
    parent = "Components"
    