DefaultContentLanguage = "en"
title = "Hugo Solstice Theme"
theme = "hugo-solstice-theme"
metaDataFormat = "yaml"
googleAnalytics = ""
themesDir = "../.."
#disableKinds = ["taxonomy", "taxonomyTerm"]

[Params]
  google_tag_manager = ""
  description = "Eclipse Foundation: Solstice theme for Hugo."
  subtitle = "Eclipse Foundation"
  seo_title_suffix = " | The Eclipse Foundation"
  keywords = ["hugo", "solstice", "eclipse foundation"]
#  logo = "images/logo/eclipse-foundation-white.svg"
#  favicon = "images/favicon.ico"
#  styles = "css/styles.css"
#  js = "js/solstice.js"
  gcse = ""
  header_wrapper_class = "header-default-bg-img"
  call_for_action_text = "Download"
  call_for_action_url = "https://www.eclipse.org/downloads"
  call_for_action_icon = "fa-download"
  show_events = true

[Author]
  name = "Christopher Guindon"
  website = "https://www.eclipse.org"
  email = "webdev@eclipse-foundation.org"
  facebook = "eclipse.org"
  twitter = "EclipseFdn"
  youtube = "EclipseFdn"
  googleplus = "+Eclipse"
  linkedin = "company/eclipse-foundation/"

[permalinks]
  news = "/:sections/:year/:month/:day/:slug/"

[taxonomies]
  category = "categories"
  tag = "tags"
  membership_level = "membership_levels"
  participation_level = "participation_levels"

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true

[[menu.main]]
    name = "Examples"
    url = "#"
    weight = 2
    
[[menu.main]]
    name = "Single Page"
    url = "/single_page/"
    weight = 1
    parent = "Examples"
    
[[menu.main]]
    name = "News"
    url = "/news/"
    weight = 2
    parent = "Examples"
    
[[menu.main]]
    name = "Membership"
    url = "/membership/"
    weight = 3
    parent = "Examples"
    
[[menu.main]]
    name = "Events"
    url = "/events/"
    weight = 3
    parent = "Examples"

[[menu.main]]
    name = "FAQ"
    url = "/faq/"
    weight = 4
    parent = "Examples"

